In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
import sys
sys.path.append("../src")
sys.path.append("../data")
from logisitic import LogisticRegression

In [3]:
df = pd.read_csv("../data/tiger.csv")
df.head()

height  weight  age  tail_length     sex
0      95     180    5           90    Male
1     102     210    7           95    Male
2      88     160    4           85  Female
3     110     230    8          100    Male
4      97     175    6           92  Female

In [4]:
df['sex'] = df['sex'].map({'Male': 0, 'Female': 1})


In [5]:
X = df[['height', 'weight', 'age', 'tail_length']].values
y = df['sex'].values 
scaler = StandardScaler()
X_normalized = scaler.fit_transform(X)
X_normalized, y

(array([[-0.6979317 , -0.65660874, -0.84615385, -0.71774056],
        [ 0.36413828,  0.61424689,  0.69230769,  0.33776026],
        [-1.76000167, -1.50384583, -1.61538462, -1.77324139],
        [ 1.57793254,  1.46148397,  1.46153846,  1.39326109],
        [-0.39448313, -0.86841801, -0.07692308, -0.29554023],
        [ 0.81931112,  1.03786543,  0.69230769,  0.97106076],
        [-1.15310455, -1.08022728, -0.84615385, -1.13994089],
        [ 0.06068971,  0.19062834, -0.07692308,  0.54886043],
        [-0.09103457, -0.44479947, -0.84615385, -0.5066404 ],
        [ 1.27448397,  1.2496747 ,  1.46153846,  1.18216093]]),
 array([0, 0, 1, 0, 1, 0, 1, 0, 1, 0]))

In [6]:
logistic = LogisticRegression(X_normalized,y)
logistic.fit()

array([-0.58976461, -0.45177284, -0.87526632, -0.45739272, -0.70592472])

In [8]:
y_pred = logistic.predict(X_normalized)
class_name = ["Male", "Female"]
logistic.confusion_matrix(y, y_pred, class_name)

╔══════════════════════════════════════════════╗
║             CONFUSION MATRIX                 ║
╠══════════════════════════════════════════════╣
║              Predicted Labels                ║
╠══════════════════════════╦══════════╦════════╣
║                          ║ Male     ║ Female ║
║                          ║   (0)    ║  (1)   ║
╠══════════════════════════╬══════════╬════════╣
║         Actual           ║          ║        ║
║         Labels           ║          ║        ║
╠══════════════════════════╬══════════╬════════╣
║     Male            ║    5     ║  1     ║
╠══════════════════════════╬══════════╬════════╣
║     Female          ║    0     ║  4     ║
╚══════════════════════════╩══════════╩════════╝

╔══════════════════════════════════════╗
║           PERFORMANCE METRICS        ║
╠══════════════════════════════════════╣
║ Accuracy:   90.00% ( 9/10)        ║
║ Precision:  80.00%                    ║
║ Recall:    100.00%                    ║
║ F1-Score:   88.89%         

array([[5, 1],
       [0, 4]])